### ISSUE TITLE
Create a winner

### ISSUE THREAD

**Issue by brianhumphreys** [ucsb-cs56-projects/cs56-games-Go#75]
As of now, the game does not end automatically win there are no more squares to move on and does not find a winner.  Fix this

**Comment by johnnyzhang1738** [comment]
f17 ok 100 points

**Comment by brianslee** [comment]
W18 Ok 100 Points

**Comment by praxideus** [comment]
This is not how the game of Go is played. The game ends and a winner is decided once both players pass in succession. It even says so in the instructions provided in this program.

This issue should be changed so that "Create a winner" is activated once both players skip their turn. However, this would require the "Skip Turn" button to work. At the moment, it does not.

**Comment by brianslee** [comment]
Issue seems to have been fixed. May be subject to reopening depending on what happens to surrender.
Closed W18.
